### ISSUE TITLE
Further questions

### ISSUE THREAD

**Issue by seekingdeep** [GibranBenitez/FASSD-Net#1]
Hi there,
here are some questions that are interesting:

1- For inferencing, can it use cpu-only?
2- How much ram memory does it require for inferencing?
3- For training, can it be trained using a single 8GB nvidia gpu?
4- can the trained model be exported to run on arm-based devices such as Raspberry Pi 4?

**Comment by seekingdeep** [comment]
@GibranBenitez @LeoRose

**Comment by LeoRose** [comment]
@seekingdeep, 
1. Yes, you can use the cpu-only inference. However, based on experimental results, we have seen that the speed performance is only about a few frames per second.
2. Depending on the model version and the image input size, the required ram for inferencing should be around 2~3 GB (with batch_size=1).
3. Yes. However, either the batch size has to be reduced or the img-size has to be downsampled (both can be done by modifying the .yml file for the specific model variation).
4. All the models run fine in arm devices. We have tested them as they are on the Nvidia Jetson family. Running the models on the Raspberry Pi 4 should be possible, too. However, the speed performance, as one can expect, is definitely going to be very slow. If possible, I suggest the use of at least the Nvidia Jetson Nano for embeeded applications.

**Comment by seekingdeep** [comment]
can message me at  muharraq@outlook.com
i can explain more

**Comment by seekingdeep** [comment]
i am surveying the feasibility of deploying the model on arm-based devices such as raspberry pi 4, while having images of size 1024*1024

i want to know using only cpu for inferencing on 1024*1024 images, how much ram is used, and what is the inferencing speed fps.

waiting for your reply

**Comment by LeoRose** [comment]
Unfortunately, we do not have any raspberry pi 4 to try that out.

**Comment by seekingdeep** [comment]
Thanks
